<?php

$modversion['name'] = '' . _AN_TITRE . '';
$modversion['version'] = 1;
$modversion['description'] = 'Pour les anniversaires des membres';
$modversion['author'] = 'Lmaix <br>http://www.bahut.com';
$modversion['credits'] = 'The XOOPS Project';
$modversion['help'] = '';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'anni.gif';
$modversion['dirname'] = 'anni';

// Blocks
$modversion['blocks'][1]['file'] = 'Anni.php';
$modversion['blocks'][1]['name'] = '' . _AN_TITRE . '';
//$modversion['blocks']['description'] = "Montre les anniversaires";
$modversion['blocks'][1]['show_func'] = 'b_anni_show';

// Menu
$modversion['hasMain'] = 1;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
